/*IN JAVASCRIPT FUNCTIONS ARE FIRST CLASS OBJECTS
JUST LIKE AN OBJECT , A FUNCTION CAN BE PASSED AS AN ARGUMENT TO A FUNCTION
A FUNCTION CAN ALSO BE RETURNED AS VALUES FROM OTHER FUNCTIONS

Any function that is passed as an argument to another function is called a CALLBACK 
FUNCTION IN JAVASCRIPT

THE FUCTIONS WHICH ACCEPTS A FUNCTION AS AN ARGUMENT OR RETURNS A FUNCTION IS CALLED A
HIGHER ORDER FUNCTION 
 
WHY WE NEED A CALLBACK FUNCTION ?
SYNCHRONOUS CALLBACK - A CALLBACK WHICH IS EXECUTED IMMEDIATLY IS CALLED SYNCHRONOUS CALLBACK
                       THESE CALLBACK METHODS ARE PASSED TO SORT, MAP , FILTER*/

function greet(name) {
  console.log(`Hello ${name}`)
}
function higherOrderFunction(CALLBACK) {
  const name = 'HIMADRI';
  CALLBACK(name);
}
higherOrderFunction(greet)





//Asyncronous CallBack
/*1.AN ASYNC CALLBACK IS A CALLBACK THAT IS OFTEN USED TO CONTINUE OR RESUME CODE EXECUTION OR RESUME CODE EXECUTION 
    AFTER AN ASYNCHRONOUS OPERATION HAS COMPLETED 
  2.CALLBACKS ARE USED TO DELAY THE EXECUTION OF FUNCTION UNTIL A PERTICULAR TIME OR EVENT HAS OCCURED 
  3.DATA FETCHING TAKES TAKES TIME AND WE CAN ONLY RUN THE FUNCTION WE WANT TO AFTER THE DATA HAS BEEN FETCHED AND NOT 
    IMMEDIATELY */

function abc() {
  console.log('Himadri paul stop talking');
}
abc(5000);

//The Traditional methods js has availabe for running code asynchronously
/* AT REGULAR INTRVAL OF TIME
   setTimeout()
   setInterval()*/
